Sources/Cocoa/Components/DataSources/XCCollectionViewComposedDataSource/XCCollectionViewDataSource.swift
Sources/Cocoa/Reusable/UICollectionView+Reusable.swift
Sources/Cocoa/Reusable/UITableView+Reusable.swift

Avoid crashes when requesting a view and datasource return nil

UICollectionView crash on supplementary view

---

Sources/Cocoa/Extensions/UIApplication+Extensions.swift

Added a new static func in UIApplication extension to provide the current visible window in an app.
It iterates through windows from top to bottom and returns the visible window. Time complexity is O(n) in worst case scenario, where n represents the number of windows in a given application.

[Feature] - Functionality to find visible window in an app

---

Sources/Swift/Extensions/Dictionary+Extensions.swift

Added not-equal func for dictionary

[Enhancement] - Dictionary Equatable

---

Sources/Cocoa/Extensions/UINavigationController+Extensions.swift
Xcore.xcodeproj/project.pbxproj

Added convenience method to push a view controller in the middle of the stack

Navigation Controller extension

---

Example/Supporting Files/XcodeWarnings.xcconfig
Example/ViewControllers/RootViewController.swift
Example/ViewControllers/Showcase/ExampleArrowOptions.swift
Example/ViewControllers/Showcase/ExampleDynamicTableViewController.swift
Sources/Cocoa/Components/DataSources/XCCollectionViewComposedDataSource/XCCollectionViewComposedDataSource.swift
Sources/Cocoa/Components/DataSources/XCTableViewComposedDataSource/XCTableViewComposedDataSource.swift
Sources/Cocoa/Components/FeatureFlag/Providers/CompositeFeatureFlagProvider.swift
Sources/Cocoa/Components/HUD/HUD.swift
Sources/Cocoa/Components/Picker/BasicPickerModel.swift
Sources/Cocoa/Components/Picker/DatePicker.swift
Sources/Cocoa/Components/Picker/DrawerScreen.swift
Sources/Cocoa/Components/Picker/InputToolbar.swift
Sources/Cocoa/Components/Picker/Picker+Content.swift
Sources/Cocoa/Components/Picker/Picker+RowView.swift
Sources/Cocoa/Components/Picker/Picker.swift
Sources/Cocoa/Components/Picker/PickerModel.swift
Sources/Cocoa/Components/ReorderTableView.swift
Sources/Cocoa/Components/SplitScreenViewController.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/CompositeImageFetcher.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/ImageDownloader.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/ImageFetcher.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/LocalImageFetcher.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/RemoteImageFetcher.swift
Sources/Cocoa/Components/UIImage/ImageFetcher/UIImage+Fetcher.swift
Sources/Cocoa/Components/UIImage/ImageRepresentable/PluginImage.swift
Sources/Cocoa/Components/UIImage/ImageRepresentable/UIImage+ImageRepresentable.swift
Sources/Cocoa/Components/UIImage/ImageRepresentable/UIImageView+ImageRepresentable.swift
Sources/Cocoa/Components/UIImage/ImageTransform/CompositeImageTransform.swift
Sources/Swift/Components/Either.swift
Xcore.xcodeproj/project.pbxproj

- Added Picker view with built-in date picker.

UI Components

---

Example/ViewControllers/RootViewController.swift
Example/ViewControllers/Showcase/FeedExample/FeedDataSource.swift
Example/ViewControllers/Showcase/FeedExample/FeedViewController.swift
Sources/Cocoa/Components/DynamicTableView/DynamicTableViewCell.swift
Sources/Cocoa/Components/Layouts/Adapters/XCCollectionViewTileLayoutAdapter.swift
Sources/Cocoa/Components/Layouts/TileLayout/XCCollectionViewDelegateTileLayout.swift
Sources/Cocoa/Components/Layouts/TileLayout/XCCollectionViewTileLayout.swift
Sources/Cocoa/Components/Picker/DatePicker.swift

Fixed date picker not setting up selected date
Added conditional tile shadow
Added corner radius per tile

Date Picker Fix, Conditional Tile Shadow + CornerRadius

---

Example/ViewControllers/Showcase/SeparatorViewController.swift
Sources/Cocoa/Components/SeparatorView.swift

Fixed bug on dotted vertical separator not drawing correctly
Cleaned up code using shape layers directly
Added new pattern style which lets you customize how you want it to look
Added ability to set up automatic thickness to a different value

Separator View [Fix/Enhancement]

---

Sources/Cocoa/Components/SeparatorView.swift

Pixel perfect lines
Fixed line cap exceeding bounds

SeparatorView [FIX]

---

Example/ViewControllers/RootViewController.swift
Sources/Cocoa/Components/Picker/DrawerScreen.swift

Drawer screen dismiss gesture recognizer overriding other gesture recognizers fixed

Drawer Screen [Fix]

---

Sources/Cocoa/ThirdParty/MarkdownKit/MarkdownKit+UIKit.swift

- Added a 'customElements' property to MarkupText.Appearance, which are appended to the existing custom elements when configuring the parser.

MarkupText: Added support for adding custom elements to the parser.

---

Sources/Cocoa/Reusable/UICollectionView+Reusable.swift

prevents a crash when querying layout attributes that are not currentl…y present

[Hotfix] Layout Attributes

---

Example/ViewControllers/Showcase/FeedExample/Alerts/AlertDataSource.swift
Sources/Cocoa/Components/Layouts/TileLayout/XCCollectionViewTileLayout.swift

Applying vertical spacing for current section and applying it always on the sections that has items

Tile Layout Vertical Spacing[Hotfix]

---

Sources/Cocoa/Components/DataSources/XCCollectionViewComposedDataSource/XCCollectionViewDataSource.swift

Adding isEmpty variable to all datasources

Datasource convenience method

---

Sources/Cocoa/Components/HUD/HUD.swift
Sources/Cocoa/Components/Interstitials/Interstitial+Item.swift
Sources/Cocoa/Components/Picker/DrawerScreen.swift
Sources/Cocoa/Components/Picker/PickerList.swift
Sources/Cocoa/Protocols/StringRepresentable.swift

- fixed accessibility for Pickers and Drawer screen and added accessibility trait
- remove duplicate accessibility label assignment in LabelTextView
- added right accessibility to Interstitials dismiss button.

Accessibility fixes

---

Sources/Cocoa/Components/Layouts/FlowLayout/XCCollectionViewFlowLayout+Attributes.swift
Sources/Cocoa/Components/Layouts/TileLayout/XCCollectionViewTileLayout+Attributes.swift
Sources/Cocoa/Components/XCCollectionReusableView.swift
Sources/Cocoa/Components/XCCollectionViewCell.swift

Implemented isEqual in subclassed attributes for UIKit to properly recognize when to apply them
https://developer.apple.com/documentation/uikit/uicollectionviewlayoutattributes

[Hotfix] UICollectionViewLayoutAttributes Subclass Fix

---

Example/ViewControllers/RootViewController.swift
Example/ViewControllers/Showcase/ExampleLabelInsetViewController.swift
Sources/Cocoa/Extensions/UILabel+Extensions.swift
Xcore.xcodeproj/project.pbxproj

Fixed calculations for applying contentInset correctly
Added example to test and check visually the contentInset property in different contexts

UILabel extension content inset fix

---

Sources/Cocoa/Components/CarouselView/CarouselView.swift

CarouselView: add support for disabling scrolling in the underlying collection view

[CarouselView] Add `isScrollEnabled` Property

---

Sources/Cocoa/Components/SearchBarView.swift

Ability to change text for search bar

Search bar text

---

Example/ViewControllers/RootViewController.swift
Sources/Cocoa/Components/Picker/DrawerScreen.swift

fixed issue where the hud was in a weird state when hiding/showing the drawer

Drawer fix

---

Sources/Cocoa/Components/SearchBarView.swift

Search bar listens to keyboard changes and adjusts cancel button automatically

Search Bar - Cancel Button

---

Sources/Cocoa/Extensions/NotificationCenter+Extensions.swift

- Added notification for color blindness accessibility option

Textfield accessibility updates

---

Sources/Cocoa/Components/LabelTextView.swift

- Handle is accessibility element based on isTitle property

LabelTextView accessibility updates

---

Sources/Cocoa/Components/WebView/WebViewController.swift

- Added accessibility notification to force voice over to focus on first element on screen

Web View Controller accessibility updates

---

Sources/Cocoa/Components/WebView/WebViewController.swift

This is a suggestion on how to support applications URLs like `sms:` or `mailto:` when they are called inside WebView.
Testing `mailto:` has to be done on a physical device, otherwise, it will not work.
For safety use, I would like to also make one more condition before canceling navigation action and taking it over to `open` function but problem is that webs are not consistent and they do not report the correct value we can use to do "safety check"

[WKWebView] - handle application actions

---

Sources/Xcore/Swift/Components/Validation/ValidationRule+Rules.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Configuration/TextFieldConfiguration+Custom.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Configuration/TextFieldConfiguration+General.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Configuration/TextFieldConfiguration+SSN.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Configuration/TextFieldConfiguration.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Formatter/CustomTextFieldFormatter+Mask.swift
Sources/Xcore/SwiftUI/Components/DynamicTextField/Formatter/CustomTextFieldFormatter.swift

Added masks for ssn and phone numbers
Added additional validation for phone numbers (10 digits required)

Custom masking for DynamicTextField

---

Tests/XcoreTests/AppInfoTests.swift
Tests/XcoreTests/Clients/AppPhaseClientTests.swift
Tests/XcoreTests/Clients/AppStatus+SessionStateTests.swift
Tests/XcoreTests/Clients/HapticFeedbackClientTests.swift
Tests/XcoreTests/Clients/OpenURLClientTests.swift
Tests/XcoreTests/Clients/PasteboardClientTests.swift
Tests/XcoreTests/CryptographyTests.swift
Tests/XcoreTests/DependencyTests.swift
Tests/XcoreTests/DictionaryTests.swift
Tests/XcoreTests/EmptyTests.swift
Tests/XcoreTests/FailableTests.swift
Tests/XcoreTests/IdentifierTests.swift
Tests/XcoreTests/ImageRepresentableTests.swift
Tests/XcoreTests/ImageTransformTests.swift
Tests/XcoreTests/StringTests.swift
Tests/XcoreTests/UUIDTests.swift

See also [Migrating a test from XCTest](https://developer.apple.com/documentation/testing/migratingfromxctest) guide.

Start converting tests from XCTest to Swift Testing.
