zmian/xcore

Sources/Cocoa/Extensions/UIViewController+HidesBottomBarWhenPushed.swift, Sources/Cocoa/Protocols/KeyboardObservable.swift
- fixed issue when keyboard height wasn't passing back the expected value;
- subscribe/unsubscribe keyboard event observers on more appropriate UIViewController instance methods.
=> [Bugfix] - Keyboard Notification Management

Sources/Cocoa/Components/Picker/DatePicker.swift
The done button in the picker when pressed triggers the callback (in case the user didn't do any change so it will put the default value)
=> Date Picker - Done Button

Sources/Cocoa/Components/WebView/WebViewController.swift
Instead of setting the web view's content inset, modify the frame to account for the safe area and toolbar.
=> [WebViewController] Safer content insets

Sources/Cocoa/Components/Picker/PickerList.swift
* Added a way to trigger partial updates of the table to avoid interfering with touch events.
* Use KVO observing to manage the auto-sizing of the table view, since it could get out-of-sync and might be resized unexpectedly.
=> PickerList Improvements

Sources/Cocoa/Extensions/UIButton/UIButton+Extensions.swift
Currently, we have two features and they have been not cooperated as was expected.
Feature 1:
- buttons smaller then 44p will have a bigger touchpoint
Feature 2: 
- buttons can expand the touch area
The second one was not working due to the first one so I have fixed the first one and keep the functionality of it so now both work.
=> [Fix] Button's touchAreaEdgeInsets accepted in hitTest

Sources/Cocoa/Components/CarouselView/CarouselCollectionView.swift, Sources/Cocoa/Components/CarouselView/CarouselView.swift
> When configuring the view with new items, the currently selected index is now explicitly set, instead of defaulting to 0.
The previous behavior would cause issues where container classes (such as CarouselView) would have a selected index out of sync from the CarouselCollectionView instance. It would also cause problems if the view is used in a table or collection cell since the index would be reset when the cell is reused.
=> CarouselCollectionView Fix

Sources/Cocoa/Components/Currency/CurrencyFormatter/CurrencyFormatter+Format.swift, Sources/Cocoa/Components/Currency/CurrencyFormatter/CurrencyFormatter.swift, Sources/Cocoa/Components/Currency/Money/Money+Components+Font.swift, Sources/Cocoa/Components/Currency/Money/Money.swift, UnitTests/Components/Currency/CurrencyFormatterTests.swift, UnitTests/Components/Currency/MoneyTests.swift
Fix for Money Format on ios 12.0
Allow to configure Money with empty font (so it takes the uilabel one as default)
=> Money format

Sources/Cocoa/Components/Layouts/TileLayout/XCCollectionViewTileLayout.swift
fixed issue where tile layout wasn't using fixed footer height
=> TileLayout Footer Height

Sources/Cocoa/Components/SearchBarView.swift
When the search loses focus, iOS automatically disables the Cancel button, making the user to have to tap twice (get focus, then cancel) if they want to cancel
The fix for this is to search the internal subview that is the cancel button and enable it when UIKit disables it, it's a `hack` that might not work in future versions if they change the hierarchy of the search bar, but it's harmless if that happens (no risk of crashes, no use of private api)
=> [Fix] Search bar cancel grayedout

Sources/Cocoa/Components/SearchBarView.swift
Making search bar hide/show cancel button only when searchBar text did end editing
=> [Fix] Search bar responding to search events rather than keyboard

Sources/Cocoa/Components/LabelTextView.swift, Sources/Cocoa/Extensions/UIFont/UIFont+App.swift, Sources/Cocoa/Extensions/UIFont/UIFont+Extensions.swift, Sources/Cocoa/Extensions/UILabel+Extensions.swift
- add text style to font descriptor when using app method to set font
- override accessibility traits on label text view
- override accessibility traits on UILabel
I am proposing this change to LabelTextView and UILabel to solve the issue where we forget to add accessibility traits = .header when the text is a title. This will apply the accessibility trait automatically.  
Basically, when the text style is title1, 2, 3, or headline the default trait is .header unless the user specifies a different one.
In order to do this, I had to add text style attribute to font descriptor.
=> Accessibility updates to LabelTextView and UILabel

Sources/Cocoa/Components/CarouselView/CarouselViewTypes.swift
While working with the carousel we haven't support for additionals view in the `CarouselAccessibilityItem`. This PR is proposing additional field for child elements in carousel page so the accessibility can navigate thru them and then jumps bellow the carousel or swipe up or down to adjust carousel page.
The idea come from this session: https://developer.apple.com/videos/play/wwdc2018/230/
=> [Enhancement] Support additional views for CarouselAccessibilityItem

Sources/Cocoa/Components/LabelTextView.swift
**Motivation**
I am proposing this because we need the ability to have accessible LabelTextView with even `.footnote` font-style.
This should not affect the fix proposed in https://github.com/zmian/xcore.swift/pull/70 as the only change is that we will let the client/caller set the accessibility and use it (we suppose that client/caller knows what he is doing)
@kameroli, please review and let me know what you think. 🙏
=> [FIX] Accessibility for LabelTextView

Sources/Cocoa/Components/WebView/WebViewController.swift
**Motivation**
When WebViewController is presented as modal the "Done" button is not working.
=> [FIX] Dismiss webViewController as modal when needed

Sources/Cocoa/Components/DataSources/StackingDataSource/StackingDataSource+Cells.swift
- Forced voice over to focus on cell when announcements tile stack is expanded
=> Announcements Tile accessibility updates

Sources/Cocoa/Components/DataSources/StackingDataSource/StackingDataSource.swift
- Added collapsed or extended status to announcement tile accessibility label
=> Announcements Tile accessibility update part 2

Sources/Cocoa/Components/LabelTextView.swift, Sources/Cocoa/Extensions/UITextView+Extensions.swift
I am proposing for Voice Control to use the wrapper as UIView and compute accessible elements - this is what iOS 13 is not doing correctly currently and we are trying to fix it by this PR.
After various testing of UITextView component I found out: 
- `accessibilityElements` are called only when there is more than just one link inside the component
- the variable `accessibilityElements` is not reacting to `overriding`
- adding subview to UITextView with auto layout does not calculate the correct frame (more in https://github.com/zmian/Xcore/pull/79#discussion_r497473676)
For Voice Over we will disable this behaviour to not interact with flows, we are currently supporting.
I have tested this with iOS 13 and both VoiceControl and VoiceOver - turning on/off during the flow or continually …
=> [Enhancement] Voice control links availability for LabelTextView

Sources/Cocoa/Components/Assets/ImageAssetIdentifier.swift
There is no need to restrict the ImageAssetIdentifier to non-optional value for init of UIImageView if children can work with optional.
=> [Enhancement] ImageAssetIdentifier optional init

Example/ViewControllers/Showcase/CarouselViewController.swift, Sources/Cocoa/Components/CarouselView/CarouselCollectionView.swift
**Motivation:**
Currently, when the user starts scroll between pages quickly he will get stuck at the end of scroll view (In our case he is going by pages -> 0, 1, 2, 3, 0, 0, 0, 0. So he will stay on the page with an index 0.
**Issue:**
Scroll view `contentOffset` is set only when the user's scrolling is finished - because of that the scrolling does not continue but stays on the same page while the user is still scrolling.
**FIX**
We will calculate and set `contentOffset` when it's needed by extending ranges from qual to grarterOrEqual/lessOrEqual and set offset while scrollView is scrolling.
**Other**
I would recommend testing this issue on the device and with more than just 3 items inside carouselView
=> [Fix] Quick scrolling on carrouselCollectionView

Sources/Cocoa/Components/Swizzle/SwizzleManager.swift, Sources/Cocoa/Extensions/UITableView/UITableViewCell+Extensions.swift
I am not sure why this was missing in the first place. The highlighting inside UITableViewCell was not working at all.
=> [FIX] Re-add swizzle for UITableViewCell.setHighlighted(_:animated:)

Sources/Xcore/Cocoa/Components/Currency/Money/Money+Components+Style.swift
Use `compareAmount` instead of `amount` to check if value should be abbreviated.
Otherwise negative amounts will never be abbreviated.
(address issue on Financials Tile, for Cloudfare stock)
=> Fix compareAmount usage for money abbreviation check

Sources/Xcore/Swift/Components/Dates and Timers/Date/Date+Helpers.swift
Add `middle` function to date interval as start and end aren't reliable (to group dates) due to timezone/daylight savings differences
=> Add `middle` function to date interval
